# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - README.md
  - arthur.md
  - background.md
  - research.md
  - haiku.md

footer: '<em>I laugh when I hear that the fish in the water is thirsty. -Kabir</em>'

style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
